/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentancion.Ingresa;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Clases.Articulo;
import logica.Clases.Categoria;
import logica.Clases.Ingresa;
import logica.Clases.Proveedor;
import logica.Fabrica;
import logica.Interfaces.IControladorArticulo;
import logica.Interfaces.IControladorProveedor;

/**
 *
 * @author Cristian
 */
public class MenuIngresa extends javax.swing.JPanel {

    private IControladorProveedor ICP;
    private IControladorArticulo ICA;

    private int selectedRow;
    Fabrica fabrica = Fabrica.getInstance();
    Proveedor proveedor = new Proveedor();
    Articulo articulo = new Articulo();
    ArrayList<Integer> articulo_ingresa_id = new ArrayList<>();
    ArrayList<Integer> proveedor_ingresa_id = new ArrayList<>();

    public MenuIngresa() {
        initComponents();
        this.ICP = fabrica.getIControladorProveedor();
        this.ICA = fabrica.getIControladorArticulo();
        cargarDatosEnTabla();

        tbl_Ingresa.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) { // Este chequeo asegura que solo se ejecute una vez por selección
                selectedRow = tbl_Ingresa.getSelectedRow();
                if (selectedRow != -1) {
                    // Obtener los valores de la fila seleccionada
                    String id = tbl_Ingresa.getValueAt(selectedRow, 0).toString();
                    String fecha_i = tbl_Ingresa.getValueAt(selectedRow, 1).toString();
                    String cantidad = tbl_Ingresa.getValueAt(selectedRow, 2).toString();
                    String lote = tbl_Ingresa.getValueAt(selectedRow, 3).toString();
                    String precioC = tbl_Ingresa.getValueAt(selectedRow, 4).toString();

                    // Asignar los valores a los JTextField
                    // Asignar los valores a los JTextField
                    txt_id.setText(id);
                    txt_fecha.setText(fecha_i);
                    txt_cantidad.setText(cantidad);
                    txt_lote.setText(lote);
                    txt_precioCompra.setText(precioC);

                }
            }
        });

        ArrayList<Articulo> dataArticulo = ICA.obtenerArticulos();

        for (Articulo item : dataArticulo) {

            cmb_articulo.addItem(item.getNombre());
            articulo_ingresa_id.add(item.getId());
        }

        ArrayList<Proveedor> dataProveedor = ICP.obtenerProveedor();

        for (Proveedor item : dataProveedor) {

            cmb_proveedor.addItem(item.getNombre());
            proveedor_ingresa_id.add(item.getId());
        }

    }

    private void cargarDatosEnTabla() {

        String[] columnas = {"ID", "Fecha Ingreso", "Cantidad", "Lote", "Precio Compra", "Nombre Proveedor", "Nombre Articulo","ID Proveedor","ID Articulo"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);

        ArrayList<Ingresa> ingresa = ICP.obtenerIngresa();
        for (Ingresa ingresos : ingresa) {

            Object[] fila = {
                ingresos.getIdIngresa(),
                ingresos.getFechaIngreso(),
                ingresos.getCantidad(),
                ingresos.getLote(),
                ingresos.getPrecioCompra(),
                ingresos.getProveedor().getNombre(),
                ingresos.getArticulo().getNombre(),
                ingresos.getProveedor().getId(),
                ingresos.getArticulo().getId(),
            };

            modeloTabla.addRow(fila);

        }
        tbl_Ingresa.setModel(modeloTabla);
    }

    private void eliminarIngresa(int selectedRow) {
        DefaultTableModel model = (DefaultTableModel) tbl_Ingresa.getModel();
        model.removeRow(selectedRow);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ingresa = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_fechaIngreso = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_lote = new javax.swing.JLabel();
        lbl_precioCompra = new javax.swing.JLabel();
        lbl_articulo = new javax.swing.JLabel();
        lbl_proveedor = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_lote = new javax.swing.JTextField();
        txt_precioCompra = new javax.swing.JTextField();
        cmb_articulo = new javax.swing.JComboBox<>();
        cmb_proveedor = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_ingresa = new javax.swing.JLabel();

        tbl_Ingresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha Ingreso", "Cantidad", "Lote", "Precio Compra", "Articulo", "Proveedor"
            }
        ));
        tbl_Ingresa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tbl_Ingresa);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        lbl_id.setText("ID");
        lbl_id.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(lbl_id, gridBagConstraints);

        txt_id.setEditable(false);
        txt_id.setActionCommand("txtArticuloID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(txt_id, gridBagConstraints);

        lbl_fechaIngreso.setText("Fecha de ingreso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(lbl_fechaIngreso, gridBagConstraints);

        lbl_cantidad.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(lbl_cantidad, gridBagConstraints);

        lbl_lote.setText("Lote");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(lbl_lote, gridBagConstraints);

        lbl_precioCompra.setText("Precio de compra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(lbl_precioCompra, gridBagConstraints);

        lbl_articulo.setText("Artículo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(lbl_articulo, gridBagConstraints);

        lbl_proveedor.setText("Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(lbl_proveedor, gridBagConstraints);

        txt_fecha.setActionCommand("txtArticuloNombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(txt_fecha, gridBagConstraints);

        txt_cantidad.setActionCommand("txtArticuloDesc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(txt_cantidad, gridBagConstraints);

        txt_lote.setActionCommand("txtArticuloStock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(txt_lote, gridBagConstraints);

        txt_precioCompra.setActionCommand("txtArticuloPrecio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(txt_precioCompra, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(cmb_articulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(cmb_proveedor, gridBagConstraints);

        jPanel1.setMinimumSize(new java.awt.Dimension(325, 23));
        jPanel1.setPreferredSize(new java.awt.Dimension(688, 25));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 10, 50));

        btn_agregar.setActionCommand("btn_agregar");
        btn_agregar.setLabel("Agregar");
        jPanel1.add(btn_agregar);

        btn_eliminar.setText("Eliminar");
        btn_eliminar.setActionCommand("jButtonEliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_eliminar);

        btn_modificar.setText("Modificar");
        btn_modificar.setActionCommand("jButtonModificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_modificar);

        btn_buscar.setText("Buscar");
        btn_buscar.setActionCommand("jButtonBuscar");
        jPanel1.add(btn_buscar);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lbl_ingresa.setText("Ingresar mercadería");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 324, 0, 322);
        jPanel2.add(lbl_ingresa, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        try {
            this.selectedRow = tbl_Ingresa.getSelectedRow();
            if (this.selectedRow != -1) {
                int idIngresa = (Integer) tbl_Ingresa.getValueAt(selectedRow, 0);
                // Mostrar un diálogo de confirmación
                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este ingreso?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    if (ICP.eliminarIngresa(idIngresa) == true) {
                        eliminarIngresa(this.selectedRow);
                        JOptionPane.showMessageDialog(this, "El ingreso se eliminó correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Hubo un error al eliminar el ingreso.");
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecciona una dirección para eliminar.");
            }
        } catch (Exception e) {
            e.printStackTrace(); // Puedes cambiar esto por un manejo de errores más adecuado
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        try {

            int id = Integer.parseInt(txt_id.getText());

            // Definir el formato que esperas en el campo de texto
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

            Date fecha_ingreso = formato.parse(txt_fecha.getText());

            int cantidad = Integer.parseInt(txt_cantidad.getText());
            int lote = Integer.parseInt(txt_lote.getText());
            float precioC = Float.parseFloat(txt_precioCompra.getText());
            
            int articuloCmb_id = articulo_ingresa_id.get(cmb_articulo.getSelectedIndex());
            int proveedorCmb_id = proveedor_ingresa_id.get(cmb_proveedor.getSelectedIndex());

            Articulo nuevoArticulo = new Articulo();
            nuevoArticulo.setId(articuloCmb_id);


            Proveedor nuevoProveedor = new Proveedor();
            nuevoProveedor.setId(proveedorCmb_id);

            if (fecha_ingreso==null) {
                throw new Exception("Debe completar todos los datos.");
            } else {

                Ingresa ingresa = new Ingresa(id, fecha_ingreso, cantidad, lote, precioC, nuevoProveedor, nuevoArticulo);
                ICP.modificarDatosIngresa(ingresa);

                JOptionPane.showMessageDialog(this, "El articulo se ha actualizado correctamente.", "Error", JOptionPane.INFORMATION_MESSAGE);

                txt_id.setText("");
                txt_fecha.setText("");
                txt_cantidad.setText("");
                txt_lote.setText("");
                txt_precioCompra.setText("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btn_modificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cmb_articulo;
    private javax.swing.JComboBox<String> cmb_proveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_articulo;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_fechaIngreso;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_ingresa;
    private javax.swing.JLabel lbl_lote;
    private javax.swing.JLabel lbl_precioCompra;
    private javax.swing.JLabel lbl_proveedor;
    private javax.swing.JTable tbl_Ingresa;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lote;
    private javax.swing.JTextField txt_precioCompra;
    // End of variables declaration//GEN-END:variables
}
