/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentancion;

import Presentancion.Articulo.MenuArticulo;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author vale5
 */
public class MenuPrincipal extends javax.swing.JFrame {

    
    MenuArticulo listarArticulo = new MenuArticulo();
    
    
    

    public MenuPrincipal() {
    initComponents();
    listarArticulo.setLocation(0, 0);
    jPanelContenido.setLayout(new BorderLayout()); // Asegúrate de tener BorderLayout.
    jPanelContenido.removeAll();
    jPanelContenido.add(listarArticulo, BorderLayout.CENTER);
    jPanelContenido.revalidate();
    jPanelContenido.repaint();
     this.setExtendedState(this.MAXIMIZED_BOTH);
     
        
       

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        btn_Ventas = new javax.swing.JButton();
        btn_Compras_M = new javax.swing.JButton();
        btn_Articulos = new javax.swing.JButton();
        btn_Empleado = new javax.swing.JButton();
        btn_Proveedores = new javax.swing.JButton();
        btn_Fabricante = new javax.swing.JButton();
        jPanelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanelMenu.setBackground(new java.awt.Color(0, 255, 204));
        jPanelMenu.setMaximumSize(getPreferredSize());

        btn_Ventas.setText("Ventas");

        btn_Compras_M.setText("Compras Mercaderia");
        btn_Compras_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Compras_MActionPerformed(evt);
            }
        });

        btn_Articulos.setText("Articulos");
        btn_Articulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ArticulosMouseClicked(evt);
            }
        });
        btn_Articulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArticulosActionPerformed(evt);
            }
        });

        btn_Empleado.setText("Empleado");
        btn_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpleadoActionPerformed(evt);
            }
        });

        btn_Proveedores.setText("Proveedores");

        btn_Fabricante.setText("Fabricante");
        btn_Fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FabricanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Compras_M)
                    .addComponent(btn_Proveedores)
                    .addComponent(btn_Empleado)
                    .addComponent(btn_Articulos)
                    .addComponent(btn_Ventas)
                    .addComponent(btn_Fabricante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_Compras_M)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Ventas)
                .addGap(18, 18, 18)
                .addComponent(btn_Empleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Proveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Articulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Fabricante)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jPanelContenido.setMaximumSize(getPreferredSize());

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmpleadoActionPerformed

    private void btn_ArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArticulosActionPerformed
      
    }//GEN-LAST:event_btn_ArticulosActionPerformed

    private void btn_Compras_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Compras_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Compras_MActionPerformed

    private void btn_FabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_FabricanteActionPerformed

    private void btn_ArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ArticulosMouseClicked
    listarArticulo.setLocation(0, 0);
    jPanelContenido.setLayout(new BorderLayout()); // Asegúrate de tener BorderLayout.
    jPanelContenido.removeAll();
    jPanelContenido.add(listarArticulo, BorderLayout.CENTER);
    jPanelContenido.revalidate();
    jPanelContenido.repaint();
     this.setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btn_ArticulosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Articulos;
    private javax.swing.JButton btn_Compras_M;
    private javax.swing.JButton btn_Empleado;
    private javax.swing.JButton btn_Fabricante;
    private javax.swing.JButton btn_Proveedores;
    private javax.swing.JButton btn_Ventas;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
