/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentancion.CompraMercaderia;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vale5
 */
public class Listar_CompraMercaderia extends javax.swing.JPanel {

    private DefaultTableModel modeloTabla;

    /**
     * Creates new form Listar_CompraMercaderia
     */
    public Listar_CompraMercaderia() {
        initComponents();
        cargarDatosEnTabla();
    }

    /**
     * Método para cargar los datos en la tabla.
     */
    private void cargarDatosEnTabla() {
        // Definir las columnas del modelo
        String[] columnas = {"fechaIngreso", "cantidad", "lote", "precioCompra", "proveedor", "articulo"};
                            
        // Crear el modelo de la tabla con las columnas definidas
        modeloTabla = new DefaultTableModel(columnas, 0);

        // Datos de ejemplo que se van a agregar a la tabla
        Object[][] datos = {
            {"2024-09-01", 50, "L12345", 150.75, "Distribuidora A", "Laptop Dell XPS 13"},
            {"2024-09-03", 200, "L67890", 30.50, "Proveedor B", "Teclado Mecánico RGB"},
            {"2024-09-05", 100, "L98765", 500.00, "Proveedor C", "Monitor 24 pulgadas 4K"}
        };

        // Agregar los datos al modelo
        for (Object[] fila : datos) {
            modeloTabla.addRow(fila);
        }

        // Establecer el modelo en la tabla
        jTableCompraMercaderia.setModel(modeloTabla);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompraMercaderia = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnIngresarCompraMercaderia = new javax.swing.JButton();
        jBtnEliminarCompraMercaderia = new javax.swing.JButton();
        jBtnModificarCompraMercaderia = new javax.swing.JButton();

        setMaximumSize(getPreferredSize());

        jTableCompraMercaderia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jTableCompraMercaderia.setMaximumSize(getPreferredSize());
        jScrollPane1.setViewportView(jTableCompraMercaderia);

        jPanel1.setMaximumSize(getPreferredSize());

        jBtnIngresarCompraMercaderia.setText("Nuevo Ingreso");

        jBtnEliminarCompraMercaderia.setText("Eliminar Ingreso");

        jBtnModificarCompraMercaderia.setText("Modificar Ingreso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jBtnIngresarCompraMercaderia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jBtnEliminarCompraMercaderia)
                .addGap(79, 79, 79)
                .addComponent(jBtnModificarCompraMercaderia)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIngresarCompraMercaderia)
                    .addComponent(jBtnEliminarCompraMercaderia)
                    .addComponent(jBtnModificarCompraMercaderia))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEliminarCompraMercaderia;
    private javax.swing.JButton jBtnIngresarCompraMercaderia;
    private javax.swing.JButton jBtnModificarCompraMercaderia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCompraMercaderia;
    // End of variables declaration//GEN-END:variables
}
