/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentancion.Empleado;

import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import logica.Fabrica;
import logica.Clases.Empleado;
import logica.Interfaces.IControladorEmpleado;

/**
 *
 * @author vale5
 */
public class MenuEmpleado extends javax.swing.JPanel {
    private DefaultTableModel modeloTabla;
    private IControladorEmpleado ICE;
    Fabrica fabrica = Fabrica.getInstance();

public MenuEmpleado() {
    initComponents();
    this.ICE = fabrica.getIControladoreEmpleado();
    cargarDatosEnTabla();
}

    private void cargarDatosEnTabla() {
    String[] columnas = {"ID", "Nombre Usuario", "Contraseña", "Nombre", "Apellido", "Cédula", "Rol"};
    modeloTabla = new DefaultTableModel(columnas, 0);
    
    ArrayList<Empleado> empleados = ICE.obtenerEmpleado();
    for (Empleado empleado : empleados) {
        Object[] fila = {
            empleado.getId(),
            empleado.getNombreUsuario(),
            empleado.getContraseña(),
            empleado.getNombre(),
            empleado.getApellido(),
            empleado.getCedula(),
            empleado.getRol()
        };
        modeloTabla.addRow(fila);
    }
    
    tbl_empleado.setModel(modeloTabla);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_empleado = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnIngresarEmpleado = new javax.swing.JButton();
        jBtnEliminarEmpleado = new javax.swing.JButton();
        jBtnModificarEmpleado = new javax.swing.JButton();

        setMaximumSize(getPreferredSize());

        tbl_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbl_empleado.setMaximumSize(getPreferredSize());
        jScrollPane1.setViewportView(tbl_empleado);
        tbl_empleado.getAccessibleContext().setAccessibleName("");

        jPanel1.setMaximumSize(getPreferredSize());

        jBtnIngresarEmpleado.setText("Nuevo Empleado");

        jBtnEliminarEmpleado.setText("Eliminar Empleado");

        jBtnModificarEmpleado.setText("Modificar Empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jBtnIngresarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jBtnEliminarEmpleado)
                .addGap(79, 79, 79)
                .addComponent(jBtnModificarEmpleado)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIngresarEmpleado)
                    .addComponent(jBtnEliminarEmpleado)
                    .addComponent(jBtnModificarEmpleado))
                .addGap(36, 36, 36))
        );

        jBtnIngresarEmpleado.getAccessibleContext().setAccessibleName("Crear Empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEliminarEmpleado;
    private javax.swing.JButton jBtnIngresarEmpleado;
    private javax.swing.JButton jBtnModificarEmpleado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_empleado;
    // End of variables declaration//GEN-END:variables
}
