/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentancion.Fabricante;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vale5
 */
public class Listar_Fabricante extends javax.swing.JPanel {
    private DefaultTableModel modeloTabla;

    public Listar_Fabricante() {
        initComponents();
        cargarDatosEnTabla();
    }

    private void cargarDatosEnTabla() {
        String[] columnas = {"ID", "Nombre", "Correo", "Teléfono", "Fecha Actualización", "Fecha Creación"};
        modeloTabla = new DefaultTableModel(columnas, 0);
        Object[][] datos = {
            {1, "Fabricante A", "correoA@ejemplo.com", 5551234, "2024-09-01", "2022-01-01"},
            {2, "Fabricante B", "correoB@ejemplo.com", 5555678, "2024-09-05", "2023-02-15"}
        };
        for (Object[] fila : datos) {
            modeloTabla.addRow(fila);
        }
        jTableFabricante.setModel(modeloTabla);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFabricante = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnAgregarFabricante = new javax.swing.JButton();
        jBtnEliminarFabricante = new javax.swing.JButton();
        jBtnModificarFabricante = new javax.swing.JButton();

        setMaximumSize(getPreferredSize());

        jTableFabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jTableFabricante.setMaximumSize(getPreferredSize());
        jScrollPane1.setViewportView(jTableFabricante);

        jPanel1.setMaximumSize(getPreferredSize());

        jBtnAgregarFabricante.setText("Agregar Fabricante");

        jBtnEliminarFabricante.setText("Eliminar Fabricante");

        jBtnModificarFabricante.setText("Modificar Fabricante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jBtnAgregarFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jBtnEliminarFabricante)
                .addGap(79, 79, 79)
                .addComponent(jBtnModificarFabricante)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregarFabricante)
                    .addComponent(jBtnEliminarFabricante)
                    .addComponent(jBtnModificarFabricante))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregarFabricante;
    private javax.swing.JButton jBtnEliminarFabricante;
    private javax.swing.JButton jBtnModificarFabricante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFabricante;
    // End of variables declaration//GEN-END:variables
}
